# Generated by Django 6.0.3 on 2026-08-11 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('food_item', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.userprofile')),
            ],
        ),
    ]
