# Generated by Django 6.0.3 on 2026-08-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0005_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='school',
            field=models.CharField(default='Greenfield Primary School', max_length=200),
            preserve_default=False,
        ),
    ]
