# Generated by Django 6.0.3 on 2026-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0006_inventory_category_inventory_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
