# Generated by Django 6.1 on 2026-09-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0007_delivery_delivery_time_delivery_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='batch_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
