# Generated by Django 6.0.3 on 2026-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_inventory_batch_reference_inventory_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='issue_pictures/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
        ),
    ]
