# Generated by Django 6.0.3 on 2026-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0009_issue_picture_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
