# Generated by Django 6.0.3 on 2026-09-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0011_userprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
