# Generated by Django 6.0.3 on 2026-09-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0012_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='district',
            field=models.CharField(default='Capricorn', max_length=100),
        ),
    ]
