# Generated by Django 6.0.3 on 2026-09-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0013_delivery_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learners',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
